---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
  eslint:
    enabled: true
    checks:
      callback-return:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - docs/
  - scripts/
  - tests/
  - setu.js
  - setu.min.js
